name: Build OpenGlass
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build(Debug)
      run: msbuild
    - name: Build(Release)
      run: msbuild /t:build /p:Configuration=Release'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: Build
